/**
 * Major world airports for IATA autocomplete.
 * { iata, name, city, country }
 */
export const AIRPORTS = [
  // ─── North America — USA ───────────────────────────────────────────────────
  { iata: 'ATL', name: 'Hartsfield-Jackson Atlanta International', city: 'Atlanta',        country: 'US' },
  { iata: 'LAX', name: 'Los Angeles International',                city: 'Los Angeles',    country: 'US' },
  { iata: 'ORD', name: "O'Hare International",                     city: 'Chicago',        country: 'US' },
  { iata: 'DFW', name: 'Dallas/Fort Worth International',          city: 'Dallas',         country: 'US' },
  { iata: 'DEN', name: 'Denver International',                     city: 'Denver',         country: 'US' },
  { iata: 'JFK', name: 'John F. Kennedy International',            city: 'New York',       country: 'US' },
  { iata: 'LGA', name: 'LaGuardia Airport',                        city: 'New York',       country: 'US' },
  { iata: 'EWR', name: 'Newark Liberty International',             city: 'Newark',         country: 'US' },
  { iata: 'SFO', name: 'San Francisco International',              city: 'San Francisco',  country: 'US' },
  { iata: 'SEA', name: 'Seattle-Tacoma International',             city: 'Seattle',        country: 'US' },
  { iata: 'LAS', name: 'Harry Reid International',                 city: 'Las Vegas',      country: 'US' },
  { iata: 'MCO', name: 'Orlando International',                    city: 'Orlando',        country: 'US' },
  { iata: 'MIA', name: 'Miami International',                      city: 'Miami',          country: 'US' },
  { iata: 'CLT', name: 'Charlotte Douglas International',          city: 'Charlotte',      country: 'US' },
  { iata: 'PHX', name: 'Phoenix Sky Harbor International',         city: 'Phoenix',        country: 'US' },
  { iata: 'IAH', name: 'George Bush Intercontinental',             city: 'Houston',        country: 'US' },
  { iata: 'HOU', name: 'William P. Hobby Airport',                 city: 'Houston',        country: 'US' },
  { iata: 'BOS', name: 'Logan International',                      city: 'Boston',         country: 'US' },
  { iata: 'MSP', name: 'Minneapolis-Saint Paul International',     city: 'Minneapolis',    country: 'US' },
  { iata: 'DTW', name: 'Detroit Metropolitan Wayne County',        city: 'Detroit',        country: 'US' },
  { iata: 'FLL', name: 'Fort Lauderdale-Hollywood International',  city: 'Fort Lauderdale',country: 'US' },
  { iata: 'PHL', name: 'Philadelphia International',               city: 'Philadelphia',   country: 'US' },
  { iata: 'BWI', name: 'Baltimore/Washington International',       city: 'Baltimore',      country: 'US' },
  { iata: 'DCA', name: 'Ronald Reagan Washington National',        city: 'Washington DC',  country: 'US' },
  { iata: 'IAD', name: 'Washington Dulles International',          city: 'Washington DC',  country: 'US' },
  { iata: 'MDW', name: 'Chicago Midway International',             city: 'Chicago',        country: 'US' },
  { iata: 'SAN', name: 'San Diego International',                  city: 'San Diego',      country: 'US' },
  { iata: 'TPA', name: 'Tampa International',                      city: 'Tampa',          country: 'US' },
  { iata: 'PDX', name: 'Portland International',                   city: 'Portland',       country: 'US' },
  { iata: 'HNL', name: 'Daniel K. Inouye International',           city: 'Honolulu',       country: 'US' },
  { iata: 'AUS', name: 'Austin-Bergstrom International',           city: 'Austin',         country: 'US' },
  { iata: 'BNA', name: 'Nashville International',                  city: 'Nashville',      country: 'US' },
  { iata: 'SLC', name: 'Salt Lake City International',             city: 'Salt Lake City', country: 'US' },
  { iata: 'STL', name: 'St. Louis Lambert International',          city: 'St. Louis',      country: 'US' },
  { iata: 'MCI', name: 'Kansas City International',                city: 'Kansas City',    country: 'US' },
  { iata: 'RDU', name: 'Raleigh-Durham International',             city: 'Raleigh',        country: 'US' },
  { iata: 'MSY', name: 'Louis Armstrong New Orleans International',city: 'New Orleans',    country: 'US' },
  { iata: 'SMF', name: 'Sacramento International',                 city: 'Sacramento',     country: 'US' },
  { iata: 'SJC', name: 'Norman Y. Mineta San Jose International',  city: 'San Jose',       country: 'US' },
  { iata: 'OAK', name: 'Oakland International',                    city: 'Oakland',        country: 'US' },
  { iata: 'RSW', name: 'Southwest Florida International',          city: 'Fort Myers',     country: 'US' },
  { iata: 'MKE', name: 'Milwaukee Mitchell International',         city: 'Milwaukee',      country: 'US' },
  { iata: 'PIT', name: 'Pittsburgh International',                 city: 'Pittsburgh',     country: 'US' },
  { iata: 'CLE', name: 'Cleveland Hopkins International',          city: 'Cleveland',      country: 'US' },
  { iata: 'IND', name: 'Indianapolis International',               city: 'Indianapolis',   country: 'US' },
  { iata: 'CVG', name: 'Cincinnati/Northern Kentucky International',city: 'Cincinnati',    country: 'US' },
  { iata: 'CMH', name: 'John Glenn Columbus International',        city: 'Columbus',       country: 'US' },
  { iata: 'SAT', name: 'San Antonio International',                city: 'San Antonio',    country: 'US' },
  { iata: 'SNA', name: 'John Wayne Airport',                       city: 'Orange County',  country: 'US' },
  { iata: 'BUR', name: 'Hollywood Burbank Airport',                city: 'Burbank',        country: 'US' },
  { iata: 'LGB', name: 'Long Beach Airport',                       city: 'Long Beach',     country: 'US' },
  { iata: 'ONT', name: 'Ontario International',                    city: 'Ontario',        country: 'US' },
  { iata: 'OGG', name: 'Kahului Airport',                          city: 'Maui',           country: 'US' },
  { iata: 'ABQ', name: 'Albuquerque International Sunport',        city: 'Albuquerque',    country: 'US' },
  { iata: 'TUL', name: 'Tulsa International',                      city: 'Tulsa',          country: 'US' },
  { iata: 'OKC', name: 'Will Rogers World Airport',                city: 'Oklahoma City',  country: 'US' },
  { iata: 'GRR', name: 'Gerald R. Ford International',             city: 'Grand Rapids',   country: 'US' },
  { iata: 'BDL', name: 'Bradley International',                    city: 'Hartford',       country: 'US' },
  { iata: 'PVD', name: 'T.F. Green International',                 city: 'Providence',     country: 'US' },
  { iata: 'MEM', name: 'Memphis International',                    city: 'Memphis',        country: 'US' },
  { iata: 'JAX', name: 'Jacksonville International',               city: 'Jacksonville',   country: 'US' },

  // ─── North America — Canada ────────────────────────────────────────────────
  { iata: 'YYZ', name: 'Toronto Pearson International',            city: 'Toronto',        country: 'CA' },
  { iata: 'YVR', name: 'Vancouver International',                  city: 'Vancouver',      country: 'CA' },
  { iata: 'YUL', name: 'Montréal-Trudeau International',           city: 'Montreal',       country: 'CA' },
  { iata: 'YYC', name: 'Calgary International',                    city: 'Calgary',        country: 'CA' },
  { iata: 'YEG', name: 'Edmonton International',                   city: 'Edmonton',       country: 'CA' },
  { iata: 'YOW', name: 'Ottawa Macdonald-Cartier International',   city: 'Ottawa',         country: 'CA' },
  { iata: 'YHZ', name: 'Halifax Stanfield International',          city: 'Halifax',        country: 'CA' },

  // ─── Mexico ─────────────────────────────────────────────────────────────────
  { iata: 'MEX', name: 'Benito Juárez International',              city: 'Mexico City',    country: 'MX' },
  { iata: 'CUN', name: 'Cancún International',                     city: 'Cancún',         country: 'MX' },
  { iata: 'GDL', name: 'Guadalajara International',                city: 'Guadalajara',    country: 'MX' },
  { iata: 'MTY', name: 'Monterrey International',                  city: 'Monterrey',      country: 'MX' },

  // ─── Caribbean / Central America ──────────────────────────────────────────
  { iata: 'SJU', name: 'Luis Muñoz Marín International',           city: 'San Juan',       country: 'PR' },
  { iata: 'NAS', name: 'Lynden Pindling International',            city: 'Nassau',         country: 'BS' },
  { iata: 'MBJ', name: 'Sangster International',                   city: 'Montego Bay',    country: 'JM' },
  { iata: 'KIN', name: 'Norman Manley International',              city: 'Kingston',       country: 'JM' },
  { iata: 'PTY', name: 'Tocumen International',                    city: 'Panama City',    country: 'PA' },
  { iata: 'SJO', name: 'Juan Santamaría International',            city: 'San José',       country: 'CR' },
  { iata: 'SAP', name: 'Ramón Villeda Morales International',      city: 'San Pedro Sula', country: 'HN' },
  { iata: 'GUA', name: 'La Aurora International',                  city: 'Guatemala City', country: 'GT' },

  // ─── South America ──────────────────────────────────────────────────────────
  { iata: 'GRU', name: 'São Paulo/Guarulhos International',        city: 'São Paulo',      country: 'BR' },
  { iata: 'GIG', name: 'Rio de Janeiro/Galeão International',      city: 'Rio de Janeiro', country: 'BR' },
  { iata: 'CGH', name: 'Congonhas Airport',                        city: 'São Paulo',      country: 'BR' },
  { iata: 'BSB', name: 'Brasília International',                   city: 'Brasília',       country: 'BR' },
  { iata: 'BOG', name: 'El Dorado International',                  city: 'Bogotá',         country: 'CO' },
  { iata: 'MDE', name: 'José María Córdova International',         city: 'Medellín',       country: 'CO' },
  { iata: 'SCL', name: 'Arturo Merino Benítez International',      city: 'Santiago',       country: 'CL' },
  { iata: 'LIM', name: 'Jorge Chávez International',               city: 'Lima',           country: 'PE' },
  { iata: 'EZE', name: 'Ministro Pistarini International',         city: 'Buenos Aires',   country: 'AR' },
  { iata: 'AEP', name: 'Aeroparque Jorge Newbery',                 city: 'Buenos Aires',   country: 'AR' },
  { iata: 'UIO', name: 'Quito International',                      city: 'Quito',          country: 'EC' },
  { iata: 'GYE', name: 'José Joaquín de Olmedo International',     city: 'Guayaquil',      country: 'EC' },
  { iata: 'CCS', name: 'Simón Bolívar International',              city: 'Caracas',        country: 'VE' },

  // ─── Europe — UK ────────────────────────────────────────────────────────────
  { iata: 'LHR', name: 'Heathrow Airport',                         city: 'London',         country: 'GB' },
  { iata: 'LGW', name: 'London Gatwick Airport',                   city: 'London',         country: 'GB' },
  { iata: 'STN', name: 'London Stansted Airport',                  city: 'London',         country: 'GB' },
  { iata: 'LTN', name: 'London Luton Airport',                     city: 'London',         country: 'GB' },
  { iata: 'LCY', name: 'London City Airport',                      city: 'London',         country: 'GB' },
  { iata: 'MAN', name: 'Manchester Airport',                       city: 'Manchester',     country: 'GB' },
  { iata: 'EDI', name: 'Edinburgh Airport',                        city: 'Edinburgh',      country: 'GB' },
  { iata: 'GLA', name: 'Glasgow Airport',                          city: 'Glasgow',        country: 'GB' },
  { iata: 'BHX', name: 'Birmingham Airport',                       city: 'Birmingham',     country: 'GB' },
  { iata: 'BRS', name: 'Bristol Airport',                          city: 'Bristol',        country: 'GB' },

  // ─── Europe — Western ───────────────────────────────────────────────────────
  { iata: 'CDG', name: 'Charles de Gaulle Airport',                city: 'Paris',          country: 'FR' },
  { iata: 'ORY', name: 'Paris Orly Airport',                       city: 'Paris',          country: 'FR' },
  { iata: 'NCE', name: 'Nice Côte d\'Azur Airport',                city: 'Nice',           country: 'FR' },
  { iata: 'LYS', name: 'Lyon-Saint Exupéry Airport',               city: 'Lyon',           country: 'FR' },
  { iata: 'MRS', name: 'Marseille Provence Airport',               city: 'Marseille',      country: 'FR' },
  { iata: 'AMS', name: 'Amsterdam Airport Schiphol',               city: 'Amsterdam',      country: 'NL' },
  { iata: 'FRA', name: 'Frankfurt Airport',                        city: 'Frankfurt',      country: 'DE' },
  { iata: 'MUC', name: 'Munich Airport',                           city: 'Munich',         country: 'DE' },
  { iata: 'BER', name: 'Berlin Brandenburg Airport',               city: 'Berlin',         country: 'DE' },
  { iata: 'DUS', name: 'Düsseldorf Airport',                       city: 'Düsseldorf',     country: 'DE' },
  { iata: 'HAM', name: 'Hamburg Airport',                          city: 'Hamburg',        country: 'DE' },
  { iata: 'CGN', name: 'Cologne Bonn Airport',                     city: 'Cologne',        country: 'DE' },
  { iata: 'STR', name: 'Stuttgart Airport',                        city: 'Stuttgart',      country: 'DE' },
  { iata: 'MAD', name: 'Adolfo Suárez Madrid-Barajas Airport',     city: 'Madrid',         country: 'ES' },
  { iata: 'BCN', name: 'Barcelona-El Prat Airport',                city: 'Barcelona',      country: 'ES' },
  { iata: 'AGP', name: 'Málaga Airport',                           city: 'Málaga',         country: 'ES' },
  { iata: 'PMI', name: 'Palma de Mallorca Airport',                city: 'Palma',          country: 'ES' },
  { iata: 'SVQ', name: 'Seville Airport',                          city: 'Seville',        country: 'ES' },
  { iata: 'VLC', name: 'Valencia Airport',                         city: 'Valencia',       country: 'ES' },
  { iata: 'FCO', name: 'Leonardo da Vinci–Fiumicino Airport',      city: 'Rome',           country: 'IT' },
  { iata: 'CIA', name: 'Ciampino–G.B. Pastine Airport',            city: 'Rome',           country: 'IT' },
  { iata: 'MXP', name: 'Milan Malpensa Airport',                   city: 'Milan',          country: 'IT' },
  { iata: 'LIN', name: 'Milan Linate Airport',                     city: 'Milan',          country: 'IT' },
  { iata: 'BGO', name: 'Bergen Airport, Flesland',                 city: 'Bergen',         country: 'NO' },
  { iata: 'NAP', name: 'Naples International Airport',             city: 'Naples',         country: 'IT' },
  { iata: 'VCE', name: 'Venice Marco Polo Airport',                city: 'Venice',         country: 'IT' },
  { iata: 'BLQ', name: 'Bologna Guglielmo Marconi Airport',        city: 'Bologna',        country: 'IT' },
  { iata: 'LIS', name: 'Humberto Delgado Airport',                 city: 'Lisbon',         country: 'PT' },
  { iata: 'OPO', name: 'Francisco Sá Carneiro Airport',            city: 'Porto',          country: 'PT' },
  { iata: 'FAO', name: 'Faro Airport',                             city: 'Faro',           country: 'PT' },
  { iata: 'ZRH', name: 'Zurich Airport',                           city: 'Zurich',         country: 'CH' },
  { iata: 'GVA', name: 'Geneva Airport',                           city: 'Geneva',         country: 'CH' },
  { iata: 'VIE', name: 'Vienna International Airport',             city: 'Vienna',         country: 'AT' },
  { iata: 'BRU', name: 'Brussels Airport',                         city: 'Brussels',       country: 'BE' },
  { iata: 'CRL', name: 'Brussels South Charleroi Airport',         city: 'Brussels',       country: 'BE' },
  { iata: 'DUB', name: 'Dublin Airport',                           city: 'Dublin',         country: 'IE' },
  { iata: 'SNN', name: 'Shannon Airport',                          city: 'Shannon',        country: 'IE' },

  // ─── Europe — Northern ──────────────────────────────────────────────────────
  { iata: 'ARN', name: 'Stockholm Arlanda Airport',                city: 'Stockholm',      country: 'SE' },
  { iata: 'GOT', name: 'Göteborg Landvetter Airport',              city: 'Gothenburg',     country: 'SE' },
  { iata: 'CPH', name: 'Copenhagen Airport',                       city: 'Copenhagen',     country: 'DK' },
  { iata: 'OSL', name: 'Oslo Gardermoen Airport',                  city: 'Oslo',           country: 'NO' },
  { iata: 'HEL', name: 'Helsinki-Vantaa Airport',                  city: 'Helsinki',       country: 'FI' },
  { iata: 'RVN', name: 'Rovaniemi Airport',                        city: 'Rovaniemi',      country: 'FI' },
  { iata: 'RKV', name: 'Reykjavík Airport',                        city: 'Reykjavík',      country: 'IS' },
  { iata: 'KEF', name: 'Keflavík International Airport',           city: 'Reykjavík',      country: 'IS' },

  // ─── Europe — Eastern ───────────────────────────────────────────────────────
  { iata: 'WAW', name: 'Warsaw Chopin Airport',                    city: 'Warsaw',         country: 'PL' },
  { iata: 'KRK', name: 'Kraków John Paul II International',        city: 'Kraków',         country: 'PL' },
  { iata: 'PRG', name: 'Václav Havel Airport Prague',              city: 'Prague',         country: 'CZ' },
  { iata: 'BUD', name: 'Budapest Ferenc Liszt International',      city: 'Budapest',       country: 'HU' },
  { iata: 'OTP', name: 'Henri Coandă International',               city: 'Bucharest',      country: 'RO' },
  { iata: 'SOF', name: 'Sofia Airport',                            city: 'Sofia',          country: 'BG' },
  { iata: 'ATH', name: 'Athens International Airport',             city: 'Athens',         country: 'GR' },
  { iata: 'SKG', name: 'Thessaloniki Airport',                     city: 'Thessaloniki',   country: 'GR' },
  { iata: 'HER', name: 'Heraklion International Airport',          city: 'Heraklion',      country: 'GR' },
  { iata: 'KIV', name: 'Chișinău International Airport',           city: 'Chișinău',       country: 'MD' },
  { iata: 'LWO', name: 'Lviv Danylo Halytskyi International',      city: 'Lviv',           country: 'UA' },
  { iata: 'IEV', name: 'Kyiv Boryspil International',              city: 'Kyiv',           country: 'UA' },
  { iata: 'SVO', name: 'Sheremetyevo International Airport',       city: 'Moscow',         country: 'RU' },
  { iata: 'DME', name: 'Domodedovo International Airport',         city: 'Moscow',         country: 'RU' },
  { iata: 'LED', name: 'Pulkovo Airport',                          city: 'St. Petersburg', country: 'RU' },
  { iata: 'IST', name: 'Istanbul Airport',                         city: 'Istanbul',       country: 'TR' },
  { iata: 'SAW', name: 'Sabiha Gökçen International Airport',      city: 'Istanbul',       country: 'TR' },
  { iata: 'AYT', name: 'Antalya Airport',                          city: 'Antalya',        country: 'TR' },
  { iata: 'ESB', name: 'Ankara Esenboğa International Airport',    city: 'Ankara',         country: 'TR' },
  { iata: 'ZAG', name: 'Zagreb Airport',                           city: 'Zagreb',         country: 'HR' },
  { iata: 'DBV', name: 'Dubrovnik Airport',                        city: 'Dubrovnik',      country: 'HR' },
  { iata: 'SPU', name: 'Split Airport',                            city: 'Split',          country: 'HR' },
  { iata: 'BEG', name: 'Belgrade Nikola Tesla Airport',            city: 'Belgrade',       country: 'RS' },
  { iata: 'LJU', name: 'Ljubljana Jože Pučnik Airport',            city: 'Ljubljana',      country: 'SI' },
  { iata: 'SKP', name: 'Skopje International Airport',             city: 'Skopje',         country: 'MK' },
  { iata: 'TIA', name: 'Tirana International Airport',             city: 'Tirana',         country: 'AL' },
  { iata: 'RIX', name: 'Riga International Airport',               city: 'Riga',           country: 'LV' },
  { iata: 'TLL', name: 'Lennart Meri Tallinn Airport',             city: 'Tallinn',        country: 'EE' },
  { iata: 'VNO', name: 'Vilnius Airport',                          city: 'Vilnius',        country: 'LT' },

  // ─── Middle East ────────────────────────────────────────────────────────────
  { iata: 'DXB', name: 'Dubai International Airport',              city: 'Dubai',          country: 'AE' },
  { iata: 'DWC', name: 'Al Maktoum International Airport',         city: 'Dubai',          country: 'AE' },
  { iata: 'AUH', name: 'Abu Dhabi International Airport',          city: 'Abu Dhabi',      country: 'AE' },
  { iata: 'DOH', name: 'Hamad International Airport',              city: 'Doha',           country: 'QA' },
  { iata: 'KWI', name: 'Kuwait International Airport',             city: 'Kuwait City',    country: 'KW' },
  { iata: 'BAH', name: 'Bahrain International Airport',            city: 'Manama',         country: 'BH' },
  { iata: 'RUH', name: 'King Khalid International Airport',        city: 'Riyadh',         country: 'SA' },
  { iata: 'JED', name: 'King Abdulaziz International Airport',     city: 'Jeddah',         country: 'SA' },
  { iata: 'MCT', name: 'Muscat International Airport',             city: 'Muscat',         country: 'OM' },
  { iata: 'AMM', name: 'Queen Alia International Airport',         city: 'Amman',          country: 'JO' },
  { iata: 'BEY', name: 'Beirut-Rafic Hariri International',        city: 'Beirut',         country: 'LB' },
  { iata: 'TLV', name: 'Ben Gurion International Airport',         city: 'Tel Aviv',       country: 'IL' },
  { iata: 'BGW', name: 'Baghdad International Airport',            city: 'Baghdad',        country: 'IQ' },
  { iata: 'IKA', name: 'Imam Khomeini International Airport',      city: 'Tehran',         country: 'IR' },
  { iata: 'MHD', name: 'Mashhad International Airport',            city: 'Mashhad',        country: 'IR' },
  { iata: 'DAM', name: 'Damascus International Airport',           city: 'Damascus',       country: 'SY' },

  // ─── Asia — East ────────────────────────────────────────────────────────────
  { iata: 'HND', name: 'Tokyo Haneda Airport',                     city: 'Tokyo',          country: 'JP' },
  { iata: 'NRT', name: 'Narita International Airport',             city: 'Tokyo',          country: 'JP' },
  { iata: 'KIX', name: 'Kansai International Airport',             city: 'Osaka',          country: 'JP' },
  { iata: 'ITM', name: 'Osaka Itami Airport',                      city: 'Osaka',          country: 'JP' },
  { iata: 'NGO', name: 'Chubu Centrair International Airport',     city: 'Nagoya',         country: 'JP' },
  { iata: 'CTS', name: 'New Chitose Airport',                      city: 'Sapporo',        country: 'JP' },
  { iata: 'FUK', name: 'Fukuoka Airport',                          city: 'Fukuoka',        country: 'JP' },
  { iata: 'OKA', name: 'Naha Airport',                             city: 'Okinawa',        country: 'JP' },
  { iata: 'ICN', name: 'Incheon International Airport',            city: 'Seoul',          country: 'KR' },
  { iata: 'GMP', name: 'Gimpo International Airport',              city: 'Seoul',          country: 'KR' },
  { iata: 'CJU', name: 'Jeju International Airport',               city: 'Jeju',           country: 'KR' },
  { iata: 'PEK', name: 'Beijing Capital International Airport',    city: 'Beijing',        country: 'CN' },
  { iata: 'PKX', name: 'Beijing Daxing International Airport',     city: 'Beijing',        country: 'CN' },
  { iata: 'PVG', name: 'Shanghai Pudong International Airport',    city: 'Shanghai',       country: 'CN' },
  { iata: 'SHA', name: 'Shanghai Hongqiao International Airport',  city: 'Shanghai',       country: 'CN' },
  { iata: 'HKG', name: 'Hong Kong International Airport',          city: 'Hong Kong',      country: 'HK' },
  { iata: 'CAN', name: 'Guangzhou Baiyun International Airport',   city: 'Guangzhou',      country: 'CN' },
  { iata: 'SZX', name: "Shenzhen Bao'an International Airport",    city: 'Shenzhen',       country: 'CN' },
  { iata: 'CTU', name: 'Chengdu Tianfu International Airport',     city: 'Chengdu',        country: 'CN' },
  { iata: 'XIY', name: "Xi'an Xianyang International Airport",     city: "Xi'an",          country: 'CN' },
  { iata: 'WUH', name: 'Wuhan Tianhe International Airport',       city: 'Wuhan',          country: 'CN' },
  { iata: 'CKG', name: 'Chongqing Jiangbei International Airport', city: 'Chongqing',      country: 'CN' },
  { iata: 'TSN', name: 'Tianjin Binhai International Airport',     city: 'Tianjin',        country: 'CN' },
  { iata: 'KMG', name: 'Kunming Changshui International Airport',  city: 'Kunming',        country: 'CN' },
  { iata: 'TPE', name: 'Taiwan Taoyuan International Airport',     city: 'Taipei',         country: 'TW' },
  { iata: 'TSA', name: 'Taipei Songshan Airport',                  city: 'Taipei',         country: 'TW' },
  { iata: 'MFM', name: 'Macau International Airport',              city: 'Macau',          country: 'MO' },

  // ─── Asia — Southeast ───────────────────────────────────────────────────────
  { iata: 'SIN', name: 'Singapore Changi Airport',                 city: 'Singapore',      country: 'SG' },
  { iata: 'KUL', name: 'Kuala Lumpur International Airport',       city: 'Kuala Lumpur',   country: 'MY' },
  { iata: 'BKK', name: 'Suvarnabhumi Airport',                     city: 'Bangkok',        country: 'TH' },
  { iata: 'DMK', name: 'Don Mueang International Airport',         city: 'Bangkok',        country: 'TH' },
  { iata: 'HKT', name: 'Phuket International Airport',             city: 'Phuket',         country: 'TH' },
  { iata: 'CNX', name: 'Chiang Mai International Airport',         city: 'Chiang Mai',     country: 'TH' },
  { iata: 'CGK', name: 'Soekarno-Hatta International Airport',     city: 'Jakarta',        country: 'ID' },
  { iata: 'DPS', name: 'Ngurah Rai International Airport',         city: 'Bali',           country: 'ID' },
  { iata: 'MES', name: 'Kualanamu International Airport',          city: 'Medan',          country: 'ID' },
  { iata: 'SUB', name: 'Juanda International Airport',             city: 'Surabaya',       country: 'ID' },
  { iata: 'MNL', name: 'Ninoy Aquino International Airport',       city: 'Manila',         country: 'PH' },
  { iata: 'CEB', name: 'Mactan-Cebu International Airport',        city: 'Cebu',           country: 'PH' },
  { iata: 'SGN', name: 'Tan Son Nhat International Airport',       city: 'Ho Chi Minh City',country: 'VN' },
  { iata: 'HAN', name: 'Noi Bai International Airport',            city: 'Hanoi',          country: 'VN' },
  { iata: 'DAD', name: 'Da Nang International Airport',            city: 'Da Nang',        country: 'VN' },
  { iata: 'RGN', name: 'Yangon International Airport',             city: 'Yangon',         country: 'MM' },
  { iata: 'PNH', name: 'Phnom Penh International Airport',         city: 'Phnom Penh',     country: 'KH' },
  { iata: 'VTE', name: 'Wattay International Airport',             city: 'Vientiane',      country: 'LA' },

  // ─── Asia — South ───────────────────────────────────────────────────────────
  { iata: 'DEL', name: 'Indira Gandhi International Airport',      city: 'Delhi',          country: 'IN' },
  { iata: 'BOM', name: 'Chhatrapati Shivaji Maharaj International',city: 'Mumbai',         country: 'IN' },
  { iata: 'BLR', name: 'Kempegowda International Airport',         city: 'Bangalore',      country: 'IN' },
  { iata: 'MAA', name: 'Chennai International Airport',            city: 'Chennai',        country: 'IN' },
  { iata: 'HYD', name: 'Rajiv Gandhi International Airport',       city: 'Hyderabad',      country: 'IN' },
  { iata: 'CCU', name: 'Netaji Subhash Chandra Bose International',city: 'Kolkata',        country: 'IN' },
  { iata: 'AMD', name: 'Sardar Vallabhbhai Patel International',   city: 'Ahmedabad',      country: 'IN' },
  { iata: 'COK', name: 'Cochin International Airport',             city: 'Kochi',          country: 'IN' },
  { iata: 'GOI', name: 'Dabolim Airport',                          city: 'Goa',            country: 'IN' },
  { iata: 'CMB', name: 'Bandaranaike International Airport',       city: 'Colombo',        country: 'LK' },
  { iata: 'DAC', name: 'Hazrat Shahjalal International Airport',   city: 'Dhaka',          country: 'BD' },
  { iata: 'KTM', name: 'Tribhuvan International Airport',          city: 'Kathmandu',      country: 'NP' },
  { iata: 'KHI', name: 'Jinnah International Airport',             city: 'Karachi',        country: 'PK' },
  { iata: 'LHE', name: 'Allama Iqbal International Airport',       city: 'Lahore',         country: 'PK' },
  { iata: 'ISB', name: 'Islamabad International Airport',          city: 'Islamabad',      country: 'PK' },

  // ─── Central Asia ───────────────────────────────────────────────────────────
  { iata: 'TAS', name: 'Tashkent International Airport',           city: 'Tashkent',       country: 'UZ' },
  { iata: 'ALA', name: 'Almaty International Airport',             city: 'Almaty',         country: 'KZ' },
  { iata: 'NQZ', name: 'Nursultan Nazarbayev International',       city: 'Astana',         country: 'KZ' },
  { iata: 'TBS', name: 'Tbilisi International Airport',            city: 'Tbilisi',        country: 'GE' },
  { iata: 'EVN', name: 'Zvartnots International Airport',          city: 'Yerevan',        country: 'AM' },
  { iata: 'GYD', name: 'Heydar Aliyev International Airport',      city: 'Baku',           country: 'AZ' },

  // ─── Africa ─────────────────────────────────────────────────────────────────
  { iata: 'JNB', name: 'O.R. Tambo International Airport',         city: 'Johannesburg',   country: 'ZA' },
  { iata: 'CPT', name: 'Cape Town International Airport',          city: 'Cape Town',      country: 'ZA' },
  { iata: 'DUR', name: 'King Shaka International Airport',         city: 'Durban',         country: 'ZA' },
  { iata: 'CAI', name: 'Cairo International Airport',              city: 'Cairo',          country: 'EG' },
  { iata: 'HRG', name: 'Hurghada International Airport',           city: 'Hurghada',       country: 'EG' },
  { iata: 'SSH', name: 'Sharm el-Sheikh International Airport',    city: 'Sharm el-Sheikh',country: 'EG' },
  { iata: 'ADD', name: 'Addis Ababa Bole International Airport',   city: 'Addis Ababa',    country: 'ET' },
  { iata: 'NBO', name: 'Jomo Kenyatta International Airport',      city: 'Nairobi',        country: 'KE' },
  { iata: 'LOS', name: 'Murtala Muhammed International Airport',   city: 'Lagos',          country: 'NG' },
  { iata: 'ABV', name: 'Nnamdi Azikiwe International Airport',     city: 'Abuja',          country: 'NG' },
  { iata: 'CMN', name: 'Mohammed V International Airport',         city: 'Casablanca',     country: 'MA' },
  { iata: 'RAK', name: 'Marrakesh Menara Airport',                 city: 'Marrakesh',      country: 'MA' },
  { iata: 'TUN', name: 'Tunis-Carthage International Airport',     city: 'Tunis',          country: 'TN' },
  { iata: 'ALG', name: 'Houari Boumediene Airport',                city: 'Algiers',        country: 'DZ' },
  { iata: 'ACC', name: 'Kotoka International Airport',             city: 'Accra',          country: 'GH' },
  { iata: 'DAR', name: 'Julius Nyerere International Airport',     city: 'Dar es Salaam',  country: 'TZ' },
  { iata: 'JRO', name: 'Kilimanjaro International Airport',        city: 'Kilimanjaro',    country: 'TZ' },
  { iata: 'ZNZ', name: 'Zanzibar International Airport',           city: 'Zanzibar',       country: 'TZ' },
  { iata: 'LUN', name: 'Kenneth Kaunda International Airport',     city: 'Lusaka',         country: 'ZM' },
  { iata: 'EBB', name: 'Entebbe International Airport',            city: 'Entebbe',        country: 'UG' },
  { iata: 'KGL', name: 'Kigali International Airport',             city: 'Kigali',         country: 'RW' },
  { iata: 'HRE', name: 'Robert Gabriel Mugabe International',      city: 'Harare',         country: 'ZW' },
  { iata: 'MPM', name: 'Maputo International Airport',             city: 'Maputo',         country: 'MZ' },
  { iata: 'DKR', name: 'Blaise Diagne International Airport',      city: 'Dakar',          country: 'SN' },
  { iata: 'ABJ', name: 'Félix-Houphouët-Boigny International',     city: 'Abidjan',        country: 'CI' },
  { iata: 'TIP', name: 'Mitiga International Airport',             city: 'Tripoli',        country: 'LY' },
  { iata: 'KRT', name: 'Khartoum International Airport',           city: 'Khartoum',       country: 'SD' },

  // ─── Oceania ─────────────────────────────────────────────────────────────────
  { iata: 'SYD', name: 'Sydney Kingsford Smith Airport',           city: 'Sydney',         country: 'AU' },
  { iata: 'MEL', name: 'Melbourne Airport',                        city: 'Melbourne',      country: 'AU' },
  { iata: 'BNE', name: 'Brisbane Airport',                         city: 'Brisbane',       country: 'AU' },
  { iata: 'PER', name: 'Perth Airport',                            city: 'Perth',          country: 'AU' },
  { iata: 'ADL', name: 'Adelaide Airport',                         city: 'Adelaide',       country: 'AU' },
  { iata: 'OOL', name: 'Gold Coast Airport',                       city: 'Gold Coast',     country: 'AU' },
  { iata: 'CNS', name: 'Cairns Airport',                           city: 'Cairns',         country: 'AU' },
  { iata: 'DRW', name: 'Darwin International Airport',             city: 'Darwin',         country: 'AU' },
  { iata: 'AKL', name: 'Auckland Airport',                         city: 'Auckland',       country: 'NZ' },
  { iata: 'CHC', name: 'Christchurch Airport',                     city: 'Christchurch',   country: 'NZ' },
  { iata: 'WLG', name: 'Wellington Airport',                       city: 'Wellington',     country: 'NZ' },
  { iata: 'NAN', name: 'Nadi International Airport',               city: 'Nadi',           country: 'FJ' },
  { iata: 'PPT', name: "Faa'a International Airport",              city: 'Papeete',        country: 'PF' },
]

// ── Search ────────────────────────────────────────────────────────────────────

/**
 * Returns up to `limit` airports matching the query string.
 * Priority order:
 *   1. IATA code prefix (case-insensitive)
 *   2. City name prefix
 *   3. City name contains
 *   4. Airport name contains
 */
export function searchAirports(query, limit = 7) {
  if (!query || query.trim().length === 0) return []
  const q = query.trim().toUpperCase()
  const ql = q.toLowerCase()

  const tier1 = [] // IATA prefix
  const tier2 = [] // city prefix
  const tier3 = [] // city contains
  const tier4 = [] // name contains

  for (const a of AIRPORTS) {
    if (a.iata.startsWith(q)) { tier1.push(a); continue }
    const cl = a.city.toLowerCase()
    if (cl.startsWith(ql)) { tier2.push(a); continue }
    if (cl.includes(ql)) { tier3.push(a); continue }
    if (a.name.toLowerCase().includes(ql)) tier4.push(a)
  }

  return [...tier1, ...tier2, ...tier3, ...tier4].slice(0, limit)
}
