export const LANGUAGES = [
  { id: 'html',       label: 'HTML',       color: '#e34c26', desc: 'The building blocks of web pages' },
  { id: 'css',        label: 'CSS',        color: '#264de4', desc: 'Make web pages look beautiful' },
  { id: 'javascript', label: 'JavaScript', color: '#f1e05a', desc: 'Add interactivity to websites' },
  { id: 'typescript', label: 'TypeScript', color: '#3178c6', desc: 'JavaScript with types and safety' },
  { id: 'python',     label: 'Python',     color: '#3572A5', desc: 'Automate, build scripts, work with data' },
  { id: 'sql',        label: 'SQL',        color: '#e38c00', desc: 'Query and manage databases' },
  { id: 'bash',       label: 'Bash',       color: '#89e051', desc: 'Automate tasks from the terminal' },
  { id: 'java',       label: 'Java',       color: '#b07219', desc: 'Build apps, Android, backend services' },
  { id: 'go',         label: 'Go',         color: '#00acd7', desc: 'Fast, simple backend and cloud code' },
  { id: 'rust',       label: 'Rust',       color: '#dea584', desc: 'Systems programming with memory safety' },
]

export const CONCEPTS_BY_LANGUAGE = {
  html: [
    'HTML structure (head and body)',
    'Headings and paragraphs',
    'Links and images',
    'Lists (ordered and unordered)',
    'Forms and inputs',
    'Divs and spans',
    'Tables',
    'Semantic elements',
  ],
  css: [
    'Selectors',
    'Colors and backgrounds',
    'Fonts and text',
    'Box model (padding, margin, border)',
    'Flexbox layout',
    'Grid layout',
    'Width and height',
    'Hover effects and transitions',
  ],
  javascript: [
    'Variables and data types',
    'Functions',
    'Arrays and objects',
    'DOM manipulation',
    'Events and listeners',
    'Fetch API and promises',
    'Arrow functions',
    'Async and await',
    'Loops',
    'Error handling',
  ],
  typescript: [
    'Type annotations',
    'Interfaces',
    'Generics',
    'Union and intersection types',
    'Type inference',
    'Enums',
    'Classes and access modifiers',
    'Utility types',
  ],
  python: [
    'Variables',
    'Print and input',
    'Numbers and math',
    'Strings',
    'Lists',
    'If and else',
    'Loops (for and while)',
    'Functions',
    'Dictionaries',
    'File reading and writing',
  ],
  sql: [
    'SELECT queries',
    'WHERE and filtering',
    'JOINs',
    'INSERT and UPDATE',
    'Aggregate functions',
    'ORDER BY and GROUP BY',
    'CREATE TABLE',
    'Subqueries',
  ],
  bash: [
    'Variables',
    'Echo and print',
    'If statements',
    'For loops',
    'Functions',
    'File operations',
    'Piping and redirection',
    'Script arguments',
  ],
  java: [
    'Variables and types',
    'Methods',
    'Classes and objects',
    'Loops',
    'Arrays',
    'If statements',
    'String methods',
    'Scanner (user input)',
  ],
  go: [
    'Variables and types',
    'Functions',
    'Structs',
    'Slices and maps',
    'Goroutines',
    'Error handling',
    'Packages and imports',
    'Interfaces',
  ],
  rust: [
    'Variables and mutability',
    'Functions',
    'Ownership and borrowing',
    'Structs',
    'Enums and pattern matching',
    'Vectors',
    'Error handling with Result',
    'Traits',
  ],
}

export const GOALS = [
  { label: 'Build a simple web page',       language: 'html',       concept: 'HTML structure (head and body)' },
  { label: 'Add links and images',           language: 'html',       concept: 'Links and images' },
  { label: 'Create an HTML form',            language: 'html',       concept: 'Forms and inputs' },
  { label: 'Style a card layout',            language: 'css',        concept: 'Box model (padding, margin, border)' },
  { label: 'Center things with Flexbox',     language: 'css',        concept: 'Flexbox layout' },
  { label: 'Handle button clicks',           language: 'javascript', concept: 'Events and listeners' },
  { label: 'Fetch data from an API',         language: 'javascript', concept: 'Fetch API and promises' },
  { label: 'Learn Python for beginners',     language: 'python',     concept: 'Variables' },
  { label: 'Write a Python script',          language: 'python',     concept: 'Print and input' },
  { label: 'Query a database',               language: 'sql',        concept: 'SELECT queries' },
  { label: 'Automate with Bash',             language: 'bash',       concept: 'Variables' },
  { label: 'Build a Go function',            language: 'go',         concept: 'Functions' },
]
